# -*- coding: utf-8 -*-
"""data_loader.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zkpbc5o6h79qX7dst8dbIdHjuj6iaDgD
"""

import pandas as pd
from datasets import load_dataset
from sklearn.model_selection import train_test_split

def load_and_preprocess_data(dataset_name="lavita/AlpaCare-MedInstruct-52k"):

    print(f"Loading dataset: {dataset_name}...")
    dataset = load_dataset(dataset_name)
    df = dataset['train'].to_pandas()
    print("Dataset loaded successfully.")

    print("Starting data preprocessing...")
    df.dropna(subset=['instruction', 'input', 'output'], inplace=True)

    df = df[df['output'].str.strip() != '']
    print(f"Dataset size after cleaning: {len(df)} rows")

    print("Splitting data into training, validation, and test sets...")

    train_df, temp_df = train_test_split(df, test_size=0.1, random_state=42)


    val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

    print("\n--- Data Split Summary ---")
    print(f"Training set size:   {len(train_df)}")
    print(f"Validation set size: {len(val_df)}")
    print(f"Test set size:       {len(test_df)}")
    print("Data preparation complete.")

    return train_df, val_df, test_df

if __name__ == '__main__':

    print("--- Running data_loader.py as a standalone script for testing ---")
    train_data, val_data, test_data = load_and_preprocess_data()
    print("\n--- Sample of the first 5 rows of Training Data ---")
    print(train_data.head())